### ISSUE TITLE
Coloca os sites no github pages pra vc pode ver dps

### ISSUE THREAD

**Issue by vitorgouveia** [gustta03/FlexBlog#1]
Se vc for nas configurações do repositório, acessar pages (na sidebar da esquerda), vc pode deixar seu site online pra vc ver dps.

Vc tem discord? o meu é VitorAvalanche#2475, me add lá dps :)

**Comment by gustta03** [comment]
Alguns eu to colocando no ar pra testar no meu celular.

Mandei solicitação de amizade lá.
